name = "rolldoradocasino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradocasino.com.es"
HMAC_KEY = "d41afb0fc5772d580d672e36b0d0489bac3efc44f6380fbe0c43f664dc806e91"
COOKIE_NAME = "8n2"
PLAY_PATH = "visit-site"
BUTTON_ID = "p63ab20955a0e8e2c7b570d5ed038bcd3"
GATE_SALT = "ca8182e32d52b99e"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "1cur"
CTA_SELECTOR = ".play-button"
